language: csharp
mono: latest
script:
- msbuild
solution: All.sln
notifications:
  slack:
    on_failure: always
    on_pull_requests: true
    on_success: always
    rooms:
      secure: DfxPhi/mRwJOq9S/ov5InySdJc93LAsWqCsyYl3fjHqwq6QWvFfrekdP3Rka445ODpIo/3g2/e1XT02SxsMzGTZlwXuNvb2UTgNHIWQvQgQBtscHPsggV0IOBGW35emg5dr/lJzsTe4Ni+yMTNIne/BTpKXrZKv8lGwNh0eR0pWOU1pYvo0BngJsqwD26OGQectNLPD5H4zYu1R3JRfLqvG7hBT1ZcBxiQz3kXPx9oVIyckmpGAzfXQXifaE6YfRK7toiFkdAGeSIm/HYZh12rbW7MzQne90aQBx9vBoyhw6hARZS5R77J7giCcE/EzxXLyHFLKl24hjyJjuLqv4QVf+LD6G03VzXQ631QbUGsemgJKTsu1PIsdl2rq8UDlstnlegazOzZCDFQ83gKZ8d4/cHuG5vATtiIqMCZ9x/cT1uFBiJ/X4jr0njqxH0P7vPMAGId1bHN3gnyHnz5CoDdnj9Q+ldvn+Jie1aW3xgRw/E8eW07+LWepPoTvx0JReZYEEx4ITUXJTQjlZthRPUfPjzb/nzxyJWDFwhNooRdaXXtb9vMYRmlWZbrXFoXlv9zDqcb3znrket3iMKEa7uGYwUMpYrtbU33rj/QOsUWEBKDkwrNRpxEDDNQ5hA5Xp7fgrQoW9UshPyhLV36fL8+clTNCK8wIDcSYpNWF8X/E=
